/**
 * Exact styling for the Activity Log matching the FlowPacks design system.
 */
export const activityLogStyles = {
  pageWrapper: {
    maxWidth: "1080px",
    margin: "0 auto",
    padding: "24px 20px 48px 20px",
    fontFamily:
      "-apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif",
    boxSizing: "border-box",
  },
  toast: {
    position: "fixed",
    bottom: "28px",
    right: "28px",
    backgroundColor: "#111827",
    color: "#FFFFFF",
    padding: "12px 20px",
    borderRadius: "10px",
    boxShadow: "0 10px 25px rgba(0,0,0,0.2)",
    display: "flex",
    alignItems: "center",
    gap: "10px",
    fontSize: "14px",
    fontWeight: "500",
    zIndex: 10000,
    animation: "fadeIn 0.2s ease-out",
  },
  banner: {
    position: "relative",
    background: "linear-gradient(90deg, #5925D8 0%, #632DE0 55%, #5924CE 100%)",
    borderRadius: "14px",
    minHeight: "72px",
    padding: "16px 28px",
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    color: "#FFFFFF",
    boxShadow: "0 8px 24px rgba(88, 36, 206, 0.22)",
    overflow: "hidden",
    marginBottom: "20px",
    boxSizing: "border-box",
  },
  bannerCurves: {
    position: "absolute",
    top: 0,
    right: 0,
    bottom: 0,
    left: 0,
    width: "100%",
    height: "100%",
    pointerEvents: "none",
  },
  bannerSvg: {
    width: "100%",
    height: "100%",
  },
  brandGroup: {
    position: "relative",
    zIndex: 2,
    display: "flex",
    alignItems: "center",
    gap: "14px",
  },
  logoWrapper: {
    width: "44px",
    height: "44px",
    borderRadius: "10px",
    backgroundColor: "#FFFFFF",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    overflow: "hidden",
    boxShadow: "0 2px 8px rgba(0,0,0,0.12)",
    flexShrink: 0,
  },
  logoImg: {
    width: "28px",
    height: "28px",
    objectFit: "contain",
  },
  brandTitle: {
    fontSize: "20px",
    fontWeight: "700",
    letterSpacing: "-0.01em",
    color: "#FFFFFF",
    margin: 0,
  },
  brandSubtitle: {
    fontSize: "13px",
    color: "rgba(255, 255, 255, 0.85)",
    margin: "2px 0 0 0",
  },
  bannerRightGroup: {
    position: "relative",
    zIndex: 2,
    display: "flex",
    alignItems: "center",
    gap: "20px",
  },
  tagline: {
    display: "flex",
    alignItems: "center",
    gap: "8px",
    fontSize: "14px",
    fontWeight: "600",
    color: "rgba(255, 255, 255, 0.95)",
    letterSpacing: "-0.01em",
  },
  taglinePlus: {
    color: "rgba(255, 255, 255, 0.55)",
    fontWeight: "400",
  },
  backLibraryBtn: {
    display: "flex",
    alignItems: "center",
    gap: "8px",
    backgroundColor: "rgba(255, 255, 255, 0.15)",
    border: "1px solid rgba(255, 255, 255, 0.3)",
    borderRadius: "8px",
    padding: "8px 14px",
    color: "#FFFFFF",
    fontSize: "13px",
    fontWeight: "600",
    cursor: "pointer",
    transition: "background-color 0.15s ease",
    textDecoration: "none",
  },
  mainCard: {
    backgroundColor: "#FFFFFF",
    borderRadius: "16px",
    border: "1px solid #E5E7EB",
    boxShadow: "0 1px 3px rgba(0, 0, 0, 0.04)",
    padding: "24px 28px",
    boxSizing: "border-box",
  },
  topHeaderRow: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: "24px",
    flexWrap: "wrap",
    gap: "16px",
  },
  pageTitle: {
    fontSize: "18px",
    fontWeight: "700",
    color: "#111827",
    margin: 0,
    letterSpacing: "-0.01em",
  },
  controlsGroup: {
    display: "flex",
    alignItems: "center",
    gap: "10px",
    flexWrap: "wrap",
  },
  testRunBtn: {
    display: "inline-flex",
    alignItems: "center",
    gap: "6px",
    backgroundColor: "#F3EEFF",
    color: "#5C28D8",
    border: "1px solid #E0D4FC",
    borderRadius: "8px",
    padding: "8px 16px",
    fontSize: "13.5px",
    fontWeight: "600",
    cursor: "pointer",
    transition: "all 0.15s ease",
  },
  markAllReadBtn: {
    display: "inline-flex",
    alignItems: "center",
    gap: "6px",
    backgroundColor: "#FFFFFF",
    color: "#4B5563",
    border: "1px solid #E5E7EB",
    borderRadius: "8px",
    padding: "8px 16px",
    fontSize: "13.5px",
    fontWeight: "500",
    cursor: "pointer",
    transition: "all 0.15s ease",
  },
  selectWrapper: {
    position: "relative",
    display: "flex",
    alignItems: "center",
  },
  selectInput: {
    appearance: "none",
    WebkitAppearance: "none",
    backgroundColor: "#FFFFFF",
    border: "1px solid #E5E7EB",
    borderRadius: "8px",
    padding: "8px 32px 8px 14px",
    fontSize: "13.5px",
    fontWeight: "500",
    color: "#374151",
    cursor: "pointer",
    outline: "none",
  },
  selectArrow: {
    position: "absolute",
    right: "12px",
    pointerEvents: "none",
    display: "flex",
    alignItems: "center",
  },
  cardsList: {
    display: "flex",
    flexDirection: "column",
    gap: "12px",
  },
  card: {
    backgroundColor: "#FFFFFF",
    borderRadius: "12px",
    border: "1px solid #F3F4F6",
    padding: "16px 20px",
    boxShadow: "0 1px 2px rgba(0, 0, 0, 0.02)",
    transition: "border-color 0.15s ease, box-shadow 0.15s ease",
  },
  cardUnread: {
    borderColor: "#DDD6FE",
    backgroundColor: "#FAF8FF",
    boxShadow: "0 2px 6px rgba(92, 40, 216, 0.06)",
  },
  cardHeader: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: "16px",
  },
  cardLeft: {
    display: "flex",
    alignItems: "center",
    gap: "14px",
    flex: 1,
  },
  iconBox: {
    width: "42px",
    height: "42px",
    borderRadius: "10px",
    backgroundColor: "#F3EEFF",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    flexShrink: 0,
  },
  textGroup: {
    display: "flex",
    flexDirection: "column",
    gap: "2px",
  },
  recipeTitle: {
    fontSize: "15px",
    fontWeight: "700",
    color: "#111827",
    margin: 0,
  },
  summaryText: {
    fontSize: "13px",
    color: "#6B7280",
    margin: 0,
  },
  channelText: {
    fontSize: "12px",
    color: "#9CA3AF",
    margin: 0,
  },
  cardRight: {
    display: "flex",
    flexDirection: "column",
    alignItems: "flex-end",
    gap: "6px",
    flexShrink: 0,
  },
  timeText: {
    fontSize: "13px",
    color: "#6B7280",
    fontWeight: "400",
  },
  statusCompleted: {
    display: "inline-flex",
    alignItems: "center",
    gap: "4px",
    fontSize: "12px",
    fontWeight: "600",
    padding: "3px 10px",
    borderRadius: "20px",
    backgroundColor: "#ECFDF5",
    color: "#059669",
  },
  statusFailed: {
    display: "inline-flex",
    alignItems: "center",
    gap: "4px",
    fontSize: "12px",
    fontWeight: "600",
    padding: "3px 10px",
    borderRadius: "20px",
    backgroundColor: "#FEF2F2",
    color: "#DC2626",
  },
  unreadDot: {
    width: "7px",
    height: "7px",
    borderRadius: "50%",
    backgroundColor: "#5C28D8",
    display: "inline-block",
  },
  markReadBtn: {
    backgroundColor: "transparent",
    border: "none",
    padding: "0",
    fontSize: "11.5px",
    fontWeight: "600",
    color: "#5C28D8",
    cursor: "pointer",
    textDecoration: "underline",
    marginTop: "2px",
  },
  accordionToggleBtn: {
    background: "none",
    border: "none",
    color: "#9CA3AF",
    cursor: "pointer",
    padding: "2px",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
  },
  accordionBody: {
    marginTop: "14px",
    paddingTop: "12px",
    borderTop: "1px solid #F3F4F6",
  },
  accordionTitle: {
    fontSize: "11.5px",
    fontWeight: "700",
    textTransform: "uppercase",
    letterSpacing: "0.03em",
    color: "#6B7280",
    margin: "0 0 8px 0",
  },
  detailsList: {
    display: "flex",
    flexDirection: "column",
    gap: "6px",
  },
  detailItem: {
    backgroundColor: "#F9FAFB",
    borderRadius: "8px",
    padding: "8px 12px",
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    fontSize: "12.5px",
  },
  detailItemLeft: {
    display: "flex",
    alignItems: "center",
    gap: "10px",
  },
  itemImg: {
    width: "28px",
    height: "28px",
    borderRadius: "6px",
    objectFit: "cover",
    border: "1px solid #E5E7EB",
  },
  itemTitle: {
    fontWeight: "600",
    color: "#111827",
  },
  itemMsg: {
    color: "#6B7280",
    fontSize: "12px",
  },
  emptyState: {
    textAlign: "center",
    padding: "60px 20px",
    color: "#6B7280",
  },
  emptyIcon: {
    width: "48px",
    height: "48px",
    borderRadius: "50%",
    backgroundColor: "#F3EEFF",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    margin: "0 auto 12px auto",
  },
  paginationBar: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    padding: "18px 4px 0 4px",
    borderTop: "1px solid #F3F4F6",
    marginTop: "16px",
  },
  paginationInfo: {
    fontSize: "13px",
    color: "#6B7280",
  },
  paginationBtns: {
    display: "flex",
    alignItems: "center",
    gap: "8px",
  },
  pageBtn: {
    backgroundColor: "#FFFFFF",
    border: "1px solid #E5E7EB",
    borderRadius: "6px",
    padding: "6px 12px",
    fontSize: "12.5px",
    fontWeight: "500",
    color: "#374151",
    cursor: "pointer",
    textDecoration: "none",
  },
  pageBtnDisabled: {
    opacity: 0.4,
    pointerEvents: "none",
    cursor: "not-allowed",
  },
  // Modal styles
  modalOverlay: {
    position: "fixed",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: "rgba(17, 24, 39, 0.45)",
    backdropFilter: "blur(2px)",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    zIndex: 9999,
    padding: "20px",
    boxSizing: "border-box",
  },
  modalContent: {
    backgroundColor: "#FFFFFF",
    borderRadius: "16px",
    width: "100%",
    maxWidth: "520px",
    boxShadow:
      "0 20px 25px -5px rgba(0, 0, 0, 0.1), 0 10px 10px -5px rgba(0, 0, 0, 0.04)",
    border: "1px solid #E5E7EB",
    overflow: "hidden",
  },
  modalHeader: {
    padding: "18px 22px",
    borderBottom: "1px solid #F3F4F6",
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
  },
  modalTitleGroup: {
    display: "flex",
    alignItems: "center",
    gap: "10px",
  },
  modalTitle: {
    fontSize: "16px",
    fontWeight: "700",
    color: "#111827",
    margin: 0,
  },
  modalCloseBtn: {
    background: "transparent",
    border: "none",
    color: "#9CA3AF",
    cursor: "pointer",
    fontSize: "18px",
  },
  modalBody: {
    padding: "20px 22px",
  },
  formGroup: {
    marginBottom: "16px",
  },
  formLabel: {
    display: "block",
    fontSize: "13px",
    fontWeight: "600",
    color: "#374151",
    marginBottom: "6px",
  },
  modalSelect: {
    width: "100%",
    padding: "9px 12px",
    borderRadius: "8px",
    border: "1px solid #D1D5DB",
    backgroundColor: "#FFFFFF",
    fontSize: "13px",
    color: "#111827",
    outline: "none",
    boxSizing: "border-box",
  },
  recipeInfoCard: {
    backgroundColor: "#F9FAFB",
    borderRadius: "10px",
    padding: "12px 14px",
    border: "1px solid #E5E7EB",
    marginBottom: "16px",
  },
  recipeInfoTitle: {
    fontSize: "13.5px",
    fontWeight: "600",
    color: "#111827",
    margin: 0,
  },
  recipeInfoDesc: {
    fontSize: "12px",
    color: "#6B7280",
    margin: "3px 0 0 0",
    lineHeight: "1.4",
  },
  resultBox: {
    backgroundColor: "#F0FDF4",
    borderRadius: "10px",
    border: "1px solid #BBF7D0",
    padding: "12px 14px",
    marginBottom: "16px",
  },
  resultTitle: {
    fontSize: "13px",
    fontWeight: "700",
    color: "#15803D",
    margin: "0 0 3px 0",
  },
  resultDesc: {
    fontSize: "12px",
    color: "#166534",
    margin: 0,
  },
  modalFooter: {
    padding: "14px 22px",
    backgroundColor: "#F9FAFB",
    borderTop: "1px solid #F3F4F6",
    display: "flex",
    alignItems: "center",
    justifyContent: "flex-end",
    gap: "10px",
  },
  cancelBtn: {
    backgroundColor: "#FFFFFF",
    border: "1px solid #D1D5DB",
    borderRadius: "8px",
    padding: "7px 14px",
    fontSize: "13px",
    fontWeight: "600",
    color: "#374151",
    cursor: "pointer",
  },
  runSubmitBtn: {
    display: "inline-flex",
    alignItems: "center",
    gap: "6px",
    backgroundColor: "#5C28D8",
    color: "#FFFFFF",
    border: "none",
    borderRadius: "8px",
    padding: "7px 16px",
    fontSize: "13px",
    fontWeight: "600",
    cursor: "pointer",
    boxShadow: "0 1px 3px rgba(92, 40, 216, 0.3)",
  },
};
