/**
 * Central styling for the Automation Library and its child components.
 */
export const libraryStyles = {
  container: {
    maxWidth: "1080px",
    margin: "0 auto",
    padding: "24px 20px 48px 20px",
    fontFamily: "-apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif",
    boxSizing: "border-box",
  },
  toast: {
    position: "fixed",
    bottom: "28px",
    right: "28px",
    backgroundColor: "#111827",
    color: "#FFFFFF",
    padding: "12px 20px",
    borderRadius: "10px",
    boxShadow: "0 10px 25px rgba(0,0,0,0.2)",
    display: "flex",
    alignItems: "center",
    gap: "10px",
    fontSize: "14px",
    fontWeight: "500",
    zIndex: 10000,
    animation: "fadeIn 0.2s ease-out",
  },
  banner: {
    position: "relative",
    background: "linear-gradient(90deg, #5925D8 0%, #632DE0 55%, #5924CE 100%)",
    borderRadius: "14px",
    minHeight: "72px",
    padding: "16px 28px",
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    color: "#FFFFFF",
    boxShadow: "0 8px 24px rgba(88, 36, 206, 0.22)",
    overflow: "hidden",
    marginBottom: "24px",
    boxSizing: "border-box",
  },
  bannerCurves: {
    position: "absolute",
    top: 0,
    right: 0,
    bottom: 0,
    left: 0,
    width: "100%",
    height: "100%",
    pointerEvents: "none",
  },
  bannerSvg: {
    width: "100%",
    height: "100%",
  },
  brandGroup: {
    position: "relative",
    zIndex: 2,
    display: "flex",
    alignItems: "center",
    gap: "14px",
  },
  logoWrapper: {
    width: "44px",
    height: "44px",
    borderRadius: "10px",
    backgroundColor: "#FFFFFF",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    overflow: "hidden",
    boxShadow: "0 2px 8px rgba(0,0,0,0.12)",
    flexShrink: 0,
  },
  logoImg: {
    width: "28px",
    height: "28px",
    objectFit: "contain",
  },
  brandTitle: {
    fontSize: "20px",
    fontWeight: "700",
    letterSpacing: "-0.01em",
    color: "#FFFFFF",
    margin: 0,
  },
  brandSubtitle: {
    fontSize: "13px",
    color: "rgba(255, 255, 255, 0.85)",
    margin: "2px 0 0 0",
  },
  bannerRightGroup: {
    position: "relative",
    zIndex: 2,
    display: "flex",
    alignItems: "center",
    gap: "20px",
  },
  tagline: {
    display: "flex",
    alignItems: "center",
    gap: "8px",
    fontSize: "14px",
    fontWeight: "600",
    color: "rgba(255, 255, 255, 0.95)",
    letterSpacing: "-0.01em",
  },
  taglinePlus: {
    color: "rgba(255, 255, 255, 0.55)",
    fontWeight: "400",
  },
  activityLogBtn: {
    display: "flex",
    alignItems: "center",
    gap: "8px",
    backgroundColor: "rgba(255, 255, 255, 0.15)",
    border: "1px solid rgba(255, 255, 255, 0.3)",
    borderRadius: "8px",
    padding: "8px 14px",
    color: "#FFFFFF",
    fontSize: "13px",
    fontWeight: "600",
    cursor: "pointer",
    transition: "background-color 0.15s ease",
    textDecoration: "none",
  },
  filterBar: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: "16px",
    marginBottom: "20px",
    flexWrap: "wrap",
  },
  pillsList: {
    display: "flex",
    alignItems: "center",
    gap: "8px",
    flexWrap: "wrap",
  },
  pillBtn: {
    border: "none",
    padding: "7px 14px",
    borderRadius: "20px",
    fontSize: "13px",
    fontWeight: "600",
    cursor: "pointer",
    transition: "all 0.15s ease",
  },
  pillActive: {
    backgroundColor: "#5C28D8",
    color: "#FFFFFF",
    boxShadow: "0 2px 6px rgba(92, 40, 216, 0.25)",
  },
  pillInactive: {
    backgroundColor: "#FFFFFF",
    color: "#4B5563",
    border: "1px solid #E5E7EB",
  },
  searchWrapper: {
    position: "relative",
    minWidth: "240px",
  },
  searchIcon: {
    position: "absolute",
    left: "12px",
    top: "50%",
    transform: "translateY(-50%)",
    pointerEvents: "none",
  },
  searchInput: {
    width: "100%",
    padding: "8px 12px 8px 36px",
    borderRadius: "8px",
    border: "1px solid #E5E7EB",
    backgroundColor: "#FFFFFF",
    fontSize: "13px",
    color: "#1F2937",
    outline: "none",
    boxSizing: "border-box",
  },
  cardsList: {
    display: "flex",
    flexDirection: "column",
    gap: "12px",
    marginBottom: "28px",
  },
  card: {
    backgroundColor: "#FFFFFF",
    borderRadius: "12px",
    border: "1px solid #E5E7EB",
    padding: "18px 22px",
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    boxShadow: "0 1px 3px rgba(0, 0, 0, 0.04)",
    transition: "border-color 0.15s ease, box-shadow 0.15s ease",
  },
  cardLeft: {
    display: "flex",
    alignItems: "center",
    gap: "16px",
    flex: 1,
    paddingRight: "20px",
  },
  iconBox: {
    width: "44px",
    height: "44px",
    borderRadius: "10px",
    backgroundColor: "#F3EEFF",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    flexShrink: 0,
  },
  cardTitle: {
    fontSize: "15px",
    fontWeight: "600",
    color: "#111827",
    margin: "0 0 3px 0",
  },
  cardDesc: {
    fontSize: "13px",
    color: "#6B7280",
    margin: 0,
    lineHeight: "1.4",
  },
  cardRight: {
    display: "flex",
    alignItems: "center",
    gap: "14px",
    flexShrink: 0,
  },
  editBtn: {
    display: "flex",
    alignItems: "center",
    gap: "6px",
    backgroundColor: "#FFFFFF",
    border: "1px solid #D1D5DB",
    borderRadius: "8px",
    padding: "7px 14px",
    fontSize: "13px",
    fontWeight: "600",
    color: "#374151",
    cursor: "pointer",
  },
  toggleTrack: {
    width: "50px",
    height: "28px",
    borderRadius: "14px",
    border: "none",
    padding: 0,
    cursor: "pointer",
    position: "relative",
    transition: "background-color 0.2s ease",
    display: "flex",
    alignItems: "center",
  },
  toggleThumb: {
    width: "22px",
    height: "22px",
    borderRadius: "50%",
    backgroundColor: "#FFFFFF",
    boxShadow: "0 1px 3px rgba(0, 0, 0, 0.25)",
    transition: "transform 0.2s ease",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
  },
  emptyState: {
    textAlign: "center",
    padding: "48px 20px",
    backgroundColor: "#FFFFFF",
    borderRadius: "12px",
    border: "1px dashed #D1D5DB",
    color: "#6B7280",
    fontSize: "14px",
  },
  bottomBanner: {
    backgroundColor: "#FFFFFF",
    borderRadius: "14px",
    border: "1px solid #E5E7EB",
    padding: "20px 24px",
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    boxShadow: "0 1px 3px rgba(0, 0, 0, 0.04)",
  },
  bottomLeft: {
    display: "flex",
    alignItems: "center",
    gap: "14px",
  },
  sparkleBox: {
    width: "42px",
    height: "42px",
    borderRadius: "10px",
    backgroundColor: "#F3EEFF",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    flexShrink: 0,
  },
  bottomTitle: {
    fontSize: "15px",
    fontWeight: "700",
    color: "#111827",
    margin: "0 0 2px 0",
  },
  bottomSubtitle: {
    fontSize: "13px",
    color: "#6B7280",
    margin: 0,
  },
  suggestBtn: {
    display: "flex",
    alignItems: "center",
    gap: "8px",
    backgroundColor: "#5C28D8",
    border: "none",
    borderRadius: "8px",
    padding: "9px 18px",
    color: "#FFFFFF",
    fontSize: "13px",
    fontWeight: "600",
    cursor: "pointer",
    boxShadow: "0 2px 6px rgba(92, 40, 216, 0.25)",
  },
};
