/**
 * styles/settings.styles.js
 * Design system tokens and styles for the Settings page matching the UI mockup.
 */
export const settingsStyles = {
  container: {
    maxWidth: "1160px",
    margin: "0 auto",
    padding: "24px 20px 48px 20px",
    fontFamily: "-apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif",
    boxSizing: "border-box",
  },
  toast: {
    position: "fixed",
    bottom: "28px",
    right: "28px",
    backgroundColor: "#111827",
    color: "#FFFFFF",
    padding: "12px 20px",
    borderRadius: "10px",
    boxShadow: "0 10px 25px rgba(0,0,0,0.2)",
    display: "flex",
    alignItems: "center",
    gap: "10px",
    fontSize: "14px",
    fontWeight: "500",
    zIndex: 10000,
    animation: "fadeIn 0.2s ease-out",
  },
  banner: {
    position: "relative",
    background: "linear-gradient(90deg, #5925D8 0%, #632DE0 55%, #5924CE 100%)",
    borderRadius: "14px",
    minHeight: "72px",
    padding: "16px 28px",
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    color: "#FFFFFF",
    boxShadow: "0 8px 24px rgba(88, 36, 206, 0.22)",
    overflow: "hidden",
    marginBottom: "24px",
    boxSizing: "border-box",
  },
  bannerCurves: {
    position: "absolute",
    top: 0,
    right: 0,
    bottom: 0,
    left: 0,
    width: "100%",
    height: "100%",
    pointerEvents: "none",
  },
  bannerSvg: {
    width: "100%",
    height: "100%",
  },
  brandGroup: {
    position: "relative",
    zIndex: 2,
    display: "flex",
    alignItems: "center",
    gap: "14px",
  },
  logoWrapper: {
    width: "44px",
    height: "44px",
    borderRadius: "10px",
    backgroundColor: "#FFFFFF",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    overflow: "hidden",
    boxShadow: "0 2px 8px rgba(0,0,0,0.12)",
    flexShrink: 0,
  },
  brandTitle: {
    fontSize: "20px",
    fontWeight: "700",
    letterSpacing: "-0.01em",
    color: "#FFFFFF",
    margin: 0,
  },
  brandSubtitle: {
    fontSize: "13px",
    color: "rgba(255, 255, 255, 0.85)",
    margin: "2px 0 0 0",
  },
  tagline: {
    position: "relative",
    zIndex: 2,
    fontSize: "13.5px",
    fontWeight: "500",
    color: "rgba(255, 255, 255, 0.9)",
    letterSpacing: "0.02em",
  },
  sectionWrapper: {
    marginBottom: "28px",
  },
  sectionHeader: {
    marginBottom: "14px",
  },
  sectionTitle: {
    fontSize: "15px",
    fontWeight: "700",
    color: "#111827",
    margin: "0 0 3px 0",
  },
  sectionSubtitle: {
    fontSize: "13px",
    color: "#6B7280",
    margin: 0,
  },
  destinationsGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(330px, 1fr))",
    gap: "20px",
  },
  card: {
    backgroundColor: "#FFFFFF",
    borderRadius: "14px",
    border: "1px solid #E5E7EB",
    padding: "22px 20px",
    display: "flex",
    flexDirection: "column",
    justifyContent: "space-between",
    boxShadow: "0 1px 3px rgba(0, 0, 0, 0.03)",
    transition: "box-shadow 0.15s ease",
    minHeight: "290px",
    boxSizing: "border-box",
  },
  cardTop: {
    display: "flex",
    gap: "12px",
    alignItems: "flex-start",
    marginBottom: "16px",
    minHeight: "56px",
  },
  iconBox: {
    width: "40px",
    height: "40px",
    borderRadius: "10px",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    flexShrink: 0,
  },
  cardHeaderTexts: {
    flex: 1,
  },
  cardTitle: {
    fontSize: "15px",
    fontWeight: "600",
    color: "#111827",
    margin: "0 0 2px 0",
  },
  cardDesc: {
    fontSize: "12.5px",
    color: "#6B7280",
    margin: 0,
    lineHeight: "1.4",
  },
  badgeConnected: {
    display: "inline-flex",
    alignItems: "center",
    gap: "5px",
    fontSize: "11.5px",
    fontWeight: "600",
    padding: "2px 8px",
    borderRadius: "12px",
    backgroundColor: "#ECFDF5",
    color: "#059669",
    marginTop: "6px",
  },
  badgeEnabled: {
    display: "inline-flex",
    alignItems: "center",
    gap: "5px",
    fontSize: "11.5px",
    fontWeight: "600",
    padding: "2px 8px",
    borderRadius: "12px",
    backgroundColor: "#ECFDF5",
    color: "#059669",
    marginTop: "6px",
  },
  badgeDisabled: {
    display: "inline-flex",
    alignItems: "center",
    gap: "5px",
    fontSize: "11.5px",
    fontWeight: "600",
    padding: "2px 8px",
    borderRadius: "12px",
    backgroundColor: "#F3F4F6",
    color: "#6B7280",
    marginTop: "6px",
  },
  metaGrid: {
    display: "grid",
    gridTemplateColumns: "1fr 1fr",
    gap: "10px",
    margin: "12px 0 16px 0",
  },
  metaLabel: {
    fontSize: "11.5px",
    fontWeight: "500",
    color: "#6B7280",
    marginBottom: "2px",
  },
  metaValue: {
    fontSize: "13px",
    fontWeight: "600",
    color: "#111827",
    whiteSpace: "nowrap",
    overflow: "hidden",
    textOverflow: "ellipsis",
  },
  formGroup: {
    margin: "10px 0",
  },
  formLabel: {
    display: "block",
    fontSize: "12px",
    fontWeight: "600",
    color: "#374151",
    marginBottom: "5px",
  },
  input: {
    width: "100%",
    height: "36px",
    borderRadius: "8px",
    border: "1px solid #D1D5DB",
    padding: "0 12px",
    fontSize: "13px",
    color: "#111827",
    backgroundColor: "#FFFFFF",
    boxSizing: "border-box",
    outline: "none",
  },
  inputDisabled: {
    backgroundColor: "#F9FAFB",
    color: "#4B5563",
    cursor: "default",
  },
  helperText: {
    fontSize: "11.5px",
    color: "#6B7280",
    marginTop: "4px",
    lineHeight: "1.35",
  },
  cardActions: {
    display: "flex",
    alignItems: "center",
    gap: "8px",
    marginTop: "14px",
  },
  btnSecondary: {
    backgroundColor: "#FFFFFF",
    border: "1px solid #D1D5DB",
    borderRadius: "8px",
    padding: "6px 14px",
    fontSize: "12.5px",
    fontWeight: "600",
    color: "#374151",
    cursor: "pointer",
    transition: "background 0.15s ease",
  },
  btnPrimary: {
    backgroundColor: "#5C28D8",
    border: "none",
    borderRadius: "8px",
    padding: "6px 16px",
    fontSize: "12.5px",
    fontWeight: "600",
    color: "#FFFFFF",
    cursor: "pointer",
    boxShadow: "0 1px 3px rgba(92, 40, 216, 0.3)",
  },
  btnDanger: {
    backgroundColor: "#FFFFFF",
    border: "1px solid #FEE2E2",
    borderRadius: "8px",
    padding: "6px 14px",
    fontSize: "12.5px",
    fontWeight: "600",
    color: "#DC2626",
    cursor: "pointer",
  },
  toggleRow: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    marginTop: "auto",
    paddingTop: "12px",
  },
  toggleLabel: {
    fontSize: "13px",
    fontWeight: "600",
    color: "#111827",
  },
  toggleTrack: {
    width: "44px",
    height: "24px",
    borderRadius: "12px",
    border: "none",
    padding: 0,
    cursor: "pointer",
    position: "relative",
    transition: "background-color 0.2s ease",
    display: "inline-block",
    outline: "none",
    flexShrink: 0,
  },
  toggleThumb: {
    width: "18px",
    height: "18px",
    borderRadius: "50%",
    backgroundColor: "#FFFFFF",
    boxShadow: "0 1px 3px rgba(0,0,0,0.25)",
    transition: "transform 0.2s cubic-bezier(0.4, 0, 0.2, 1)",
    position: "absolute",
    top: "3px",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
  },
  // Section 2: Alert Preferences
  alertPreferencesCard: {
    backgroundColor: "#FFFFFF",
    borderRadius: "12px",
    border: "1px solid #E5E7EB",
    padding: "6px 20px",
    boxShadow: "0 1px 3px rgba(0, 0, 0, 0.03)",
  },
  prefRow: {
    display: "flex",
    alignItems: "center",
    gap: "14px",
    padding: "14px 0",
    borderBottom: "1px solid #F3F4F6",
    cursor: "pointer",
  },
  prefRowLast: {
    borderBottom: "none",
  },
  customCheckbox: {
    width: "20px",
    height: "20px",
    borderRadius: "5px",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    flexShrink: 0,
    cursor: "pointer",
    transition: "all 0.15s ease",
  },
  prefTitle: {
    fontSize: "13.5px",
    fontWeight: "600",
    color: "#111827",
    margin: "0 0 2px 0",
  },
  prefDesc: {
    fontSize: "12px",
    color: "#6B7280",
    margin: 0,
  },
};
