export const suggestStyles = {
  pageWrapper: {
    minHeight: "100vh",
    backgroundColor: "#F4F6F8",
    padding: "24px 28px 60px 28px",
    fontFamily: "-apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif",
    color: "#111827",
    boxSizing: "border-box",
  },
  contentContainer: {
    maxWidth: "880px",
    margin: "0 auto",
  },
  // Top Header Banner
  banner: {
    position: "relative",
    overflow: "hidden",
    borderRadius: "16px",
    background: "linear-gradient(90deg, #5925D8 0%, #632DE0 55%, #5924CE 100%)",
    padding: "24px 28px",
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: "24px",
    boxShadow: "0 4px 18px rgba(92, 40, 216, 0.22)",
    color: "#FFFFFF",
  },
  bannerCurves: {
    position: "absolute",
    inset: 0,
    pointerEvents: "none",
    overflow: "hidden",
  },
  bannerSvg: {
    width: "100%",
    height: "100%",
  },
  brandGroup: {
    display: "flex",
    alignItems: "center",
    gap: "14px",
    zIndex: 1,
  },
  logoWrapper: {
    width: "44px",
    height: "44px",
    backgroundColor: "#FFFFFF",
    borderRadius: "10px",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    boxShadow: "0 2px 8px rgba(0, 0, 0, 0.12)",
    flexShrink: 0,
  },
  brandTitle: {
    fontSize: "22px",
    fontWeight: "700",
    color: "#FFFFFF",
    margin: 0,
    letterSpacing: "-0.01em",
  },
  brandSubtitle: {
    fontSize: "13px",
    color: "rgba(255, 255, 255, 0.85)",
    margin: "3px 0 0 0",
    fontWeight: "400",
  },
  bannerRightGroup: {
    display: "flex",
    alignItems: "center",
    gap: "16px",
    zIndex: 1,
  },
  tagline: {
    display: "flex",
    alignItems: "center",
    gap: "8px",
    fontSize: "13px",
    color: "rgba(255, 255, 255, 0.9)",
    fontWeight: "500",
  },
  taglinePlus: {
    color: "rgba(255, 255, 255, 0.5)",
    fontSize: "12px",
  },

  // Main Card
  card: {
    backgroundColor: "#FFFFFF",
    borderRadius: "16px",
    border: "1px solid #E5E7EB",
    boxShadow: "0 1px 4px rgba(0, 0, 0, 0.04)",
    padding: "32px 36px",
    marginBottom: "24px",
  },
  introText: {
    fontSize: "14.5px",
    color: "#1F2937",
    fontWeight: "500",
    lineHeight: "1.5",
    marginBottom: "28px",
    maxWidth: "680px",
  },

  // Form Fields
  formGroup: {
    marginBottom: "22px",
  },
  label: {
    display: "block",
    fontSize: "13.5px",
    fontWeight: "600",
    color: "#111827",
    marginBottom: "6px",
  },
  subLabel: {
    display: "block",
    fontSize: "12px",
    color: "#6B7280",
    marginBottom: "6px",
  },
  input: {
    width: "100%",
    padding: "10px 14px",
    borderRadius: "8px",
    border: "1px solid #D1D5DB",
    fontSize: "13.5px",
    color: "#111827",
    backgroundColor: "#FFFFFF",
    outline: "none",
    boxSizing: "border-box",
    transition: "border-color 0.15s ease, box-shadow 0.15s ease",
  },
  textarea: {
    width: "100%",
    padding: "10px 14px",
    borderRadius: "8px",
    border: "1px solid #D1D5DB",
    fontSize: "13.5px",
    color: "#111827",
    backgroundColor: "#FFFFFF",
    outline: "none",
    boxSizing: "border-box",
    minHeight: "90px",
    resize: "vertical",
    fontFamily: "inherit",
    lineHeight: "1.45",
    transition: "border-color 0.15s ease, box-shadow 0.15s ease",
  },

  // Submit Button
  submitBtn: {
    width: "100%",
    padding: "12px 20px",
    backgroundColor: "#5C28D8",
    color: "#FFFFFF",
    border: "none",
    borderRadius: "8px",
    fontSize: "14px",
    fontWeight: "600",
    cursor: "pointer",
    boxShadow: "0 2px 6px rgba(92, 40, 216, 0.28)",
    transition: "all 0.18s ease",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    gap: "8px",
    marginTop: "8px",
  },
  submitBtnDisabled: {
    opacity: 0.65,
    cursor: "not-allowed",
  },

  // Success Confirmation Card
  successCard: {
    backgroundColor: "#FAF5FF",
    border: "1px solid #E9D5FF",
    borderRadius: "14px",
    padding: "32px 28px",
    textAlign: "center",
    margin: "12px 0",
  },
  successIconBox: {
    width: "56px",
    height: "56px",
    borderRadius: "50%",
    backgroundColor: "#EDE9FE",
    color: "#6D28D9",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    margin: "0 auto 16px auto",
  },
  successTitle: {
    fontSize: "18px",
    fontWeight: "700",
    color: "#111827",
    margin: "0 0 8px 0",
  },
  successDesc: {
    fontSize: "13.5px",
    color: "#4B5563",
    lineHeight: "1.5",
    margin: "0 auto 24px auto",
    maxWidth: "500px",
  },
  successActions: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    gap: "12px",
    flexWrap: "wrap",
  },
  secondaryBtn: {
    padding: "10px 18px",
    backgroundColor: "#FFFFFF",
    color: "#374151",
    border: "1px solid #D1D5DB",
    borderRadius: "8px",
    fontSize: "13.5px",
    fontWeight: "600",
    cursor: "pointer",
    textDecoration: "none",
    display: "inline-flex",
    alignItems: "center",
    gap: "6px",
  },
  primarySmallBtn: {
    padding: "10px 20px",
    backgroundColor: "#5C28D8",
    color: "#FFFFFF",
    border: "none",
    borderRadius: "8px",
    fontSize: "13.5px",
    fontWeight: "600",
    cursor: "pointer",
    boxShadow: "0 1px 3px rgba(92, 40, 216, 0.25)",
    display: "inline-flex",
    alignItems: "center",
    gap: "6px",
  },

  // Error Banner
  errorBanner: {
    backgroundColor: "#FEF2F2",
    border: "1px solid #FEE2E2",
    borderRadius: "8px",
    padding: "10px 14px",
    color: "#991B1B",
    fontSize: "13px",
    fontWeight: "500",
    marginBottom: "20px",
    display: "flex",
    alignItems: "center",
    gap: "8px",
  },
};
