/**
 * Styling for the global in-app notification popup toast.
 */
export const toastStyles = {
  popupWrapper: {
    position: "fixed",
    bottom: "24px",
    right: "24px",
    width: "360px",
    backgroundColor: "#FFFFFF",
    borderRadius: "14px",
    border: "1.5px solid #DDD6FE",
    boxShadow:
      "0 10px 25px -5px rgba(92, 40, 216, 0.15), 0 8px 10px -6px rgba(0, 0, 0, 0.1)",
    padding: "16px",
    zIndex: 99999,
    fontFamily:
      "-apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif",
    boxSizing: "border-box",
    animation: "slideInUp 0.25s ease-out",
  },
  popupHeader: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: "10px",
  },
  popupBadge: {
    display: "flex",
    alignItems: "center",
    gap: "6px",
  },
  pulseDot: {
    width: "8px",
    height: "8px",
    borderRadius: "50%",
    backgroundColor: "#EF4444",
    boxShadow: "0 0 0 2px rgba(239, 68, 68, 0.2)",
    display: "inline-block",
  },
  popupBadgeText: {
    fontSize: "12px",
    fontWeight: "700",
    color: "#5C28D8",
    letterSpacing: "0.02em",
    textTransform: "uppercase",
  },
  closeBtn: {
    background: "transparent",
    border: "none",
    color: "#9CA3AF",
    cursor: "pointer",
    fontSize: "14px",
    padding: "2px",
    lineHeight: "1",
  },
  popupBody: {
    display: "flex",
    alignItems: "flex-start",
    gap: "12px",
    marginBottom: "14px",
  },
  popupIconBox: {
    width: "34px",
    height: "34px",
    borderRadius: "8px",
    backgroundColor: "#F3EEFF",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    flexShrink: 0,
  },
  popupTextGroup: {
    flex: 1,
  },
  popupTitle: {
    fontSize: "13.5px",
    fontWeight: "700",
    color: "#111827",
    margin: "0 0 3px 0",
    lineHeight: "1.3",
  },
  popupDesc: {
    fontSize: "12.5px",
    color: "#4B5563",
    margin: 0,
    lineHeight: "1.4",
  },
  popupFooter: {
    display: "flex",
    alignItems: "center",
    justifyContent: "flex-end",
    gap: "8px",
    borderTop: "1px solid #F3F4F6",
    paddingTop: "10px",
  },
  markReadBtn: {
    backgroundColor: "transparent",
    border: "1px solid #E5E7EB",
    borderRadius: "6px",
    padding: "5px 10px",
    fontSize: "12px",
    fontWeight: "600",
    color: "#4B5563",
    cursor: "pointer",
  },
  viewLogBtn: {
    backgroundColor: "#5C28D8",
    border: "none",
    borderRadius: "6px",
    padding: "5px 12px",
    fontSize: "12px",
    fontWeight: "600",
    color: "#FFFFFF",
    cursor: "pointer",
    display: "flex",
    alignItems: "center",
    gap: "4px",
    boxShadow: "0 1px 3px rgba(92, 40, 216, 0.3)",
  },
};
